Switch from alpine:edge to alpine:latest for CI
dosbox-staging is currently in a broken state in edge:

ERROR: unable to select packages:
  so:libabsl_strings.so.2508.0.0 (no such package):
    required by: webrtc-audio-processing-2-2.1-r1[so:libabsl_strings.so.2508.0.0]

Signed-off-by: Jeffrey H. Johnson <johnsonjh.dev@gmail.com>